import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Counter from '@/components/ejUseState/Counter'
import TaskList from '@/components/ejUseState/TaskList'
import TaskList2 from '@/components/ejUseState/TaskList2'
import ChangeStyle from '@/components/ejUseState/ChangeStyle'
import EjApiCall from '@/components/ejUseEffect/ejApiCall'
import Clocke from '@/components/ejUseEffect/Clocke'
import FormValidation from '@/components/ejUseEffect/FormValidation'
import MemoizedFunction from '@/components/ejUseMemo/MemoizedFunction'
import CheckboxUseReducer from '@/components/ejUserReducer/CheckboxUseReducer'
import ColorNameUseRef from '@/components/ejUseRef/ColorNameUseRef'
import { MainThemeColor } from '@/components/ejUseContext/MainThemeColor/MainThemeColor'
import { ThemeContext } from '@/components/ejUseContext/context/ThemeChangeContext'

export default function Home() {
  return (
    <>
     
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>

          <Counter></Counter>
          <br/>
          <TaskList></TaskList>
          <br/>
          <TaskList2></TaskList2>
          <br/>
          <ChangeStyle></ChangeStyle>
          <br/>
          <EjApiCall></EjApiCall>
          <br/>
          <Clocke></Clocke>
          <br/>
          <FormValidation></FormValidation>
          <br/>
          <MemoizedFunction></MemoizedFunction>
          <br/>
          <CheckboxUseReducer></CheckboxUseReducer>
          <br/>
          <ColorNameUseRef></ColorNameUseRef>
  
          

      </main>
      
    </>
  )
}
